version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing-system
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billing
     
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
