<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Billing Exports History</title>

    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('images/logomsp.png') }}">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
</head>

<body>
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">
        @include('layouts.partials.header')
        @include('layouts.partials.sidebar')

        <div class="content-body">
            <div class="container-fluid">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Billing Exports History</h4>
                            <span class="ml-1">View and download billing exports</span>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard_branch') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('billing.branch') }}">Billing</a></li>
                            <li class="breadcrumb-item active">Export History</li>
                        </ol>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <h4 class="card-title mb-0">Export History</h4>

                                <div class="d-flex align-items-center">
                                    <form method="GET" action="{{ route('billing.exports.branch') }}" class="d-flex align-items-center mb-0">
                                        <input type="month"
                                               name="billing_period"
                                               class="form-control form-control-sm mr-2"
                                               value="{{ request('billing_period') }}"
                                               placeholder="Select Month"
                                               style="height: calc(1.5em + 0.5rem + 2px);">

                                        <button type="submit" class="btn btn-primary btn-sm mr-2">Filter</button>

                                        @if(request('billing_period'))
                                            <a href="{{ route('billing.exports.branch') }}" class="btn btn-secondary btn-sm mr-2">Clear</a>
                                        @endif
                                    </form>

                                    <a href="{{ route('billing.branch') }}" class="btn btn-primary btn-sm">Back to Billing</a>
                                </div>
                            </div>

                            <div class="card-body">
                                @if (session('error'))
                                    <div class="alert alert-danger alert-dismissible fade show mb-4">
                                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                                        <strong><i class="fa fa-exclamation-circle"></i> Error!</strong>
                                        {{ session('error') }}
                                    </div>
                                @endif

                                @if($exports->isEmpty())
                                    <div class="text-center py-5">
                                        <p class="text-muted mb-0">No export history available.</p>
                                    </div>
                                @else
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Billing Period</th>
                                                    <th>Generated On</th>
                                                    <th>Generated By</th>
                                                    <th>Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($exports as $export)
                                                    <tr>
                                                        <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d', $export->billing_period)->format('F Y') }}</td>
                                                        <td>{{ $export->created_at->format('M d, Y h:i A') }}</td>
                                                        <td>{{ optional($export->user)->name ?? 'Head Office' }}</td>
                                                        <td>
                                                            <a href="{{ route('billing.download-export.branch', $export->id) }}"
                                                               class="btn btn-primary btn-sm">
                                                                <i class="fa fa-download"></i> Download
                                                            </a>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="d-flex justify-content-center mt-4">
                                        {{ $exports->links('pagination::bootstrap-5') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by <a href="https://mass-specc.coop/" target="_blank">MASS-SPECC COOPERATIVE</a> 2025</p>
            </div>
        </div>
    </div>

    <script src="{{ asset('vendor/global/global.min.js') }}"></script>
    <script src="{{ asset('js/quixnav-init.js') }}"></script>
    <script src="{{ asset('js/custom.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        // Completely block DataTables before any scripts load
        window.DataTable = function() { return this; };
        window.dataTable = function() { return this; };

        // Block DataTables completely
        if (typeof $ !== 'undefined') {
            // Override jQuery DataTable functions
            $.fn.DataTable = function() {
                console.log('DataTables blocked on exports page');
                return this;
            };
            $.fn.dataTable = function() {
                console.log('DataTables blocked on exports page');
                return this;
            };

            // Block any DataTables extensions
            $.fn.dataTable.ext = {
                errMode: 'none',
                type: {},
                search: {},
                order: {},
                feature: {}
            };
        }

        // Prevent any DataTables initialization
        $(document).ready(function() {
            // Remove any display classes that might trigger DataTables
            $('table').removeClass('display');
            $('table').removeClass('dataTable');

            // Block any DataTables scripts from loading
            $('script').each(function() {
                if ($(this).attr('src') && $(this).attr('src').includes('datatables')) {
                    $(this).remove();
                }
            });

            // Override any existing DataTables
            if ($.fn.DataTable) {
                $('.dataTable').each(function() {
                    try {
                        if ($(this).hasClass('dataTable')) {
                            $(this).removeClass('dataTable');
                        }
                    } catch (e) {
                        console.log('DataTables cleanup completed');
                    }
                });
            }
        });

        // Block DataTables errors globally
        $(document).on('error.dt', function(e) {
            e.preventDefault();
            e.stopPropagation();
            return false;
        });

        // Block any DataTables related errors
        window.addEventListener('error', function(e) {
            if (e.message && e.message.includes('DataTable')) {
                e.preventDefault();
                return false;
            }
        });

        // Override console.error to block DataTables errors
        var originalConsoleError = console.error;
        console.error = function() {
            var args = Array.prototype.slice.call(arguments);
            var message = args.join(' ');
            if (message.includes('DataTable') || message.includes('Not enough data')) {
                console.log('DataTables error blocked:', message);
                return;
            }
            originalConsoleError.apply(console, arguments);
        };
    </script>
</body>
</html>
